pipeline{
    agent { label 'AGENT-1' } //jenkins node name
    environment{
        PROJECT = 'EXPENSE'     //We can use these as global variables
        COMPONENT = 'BACKEND' 
        DEPLOY_TO = "production"
    }
    options{
        disableConcurrentBuilds()  //Builds will not applt at a time
        //timeout(time: 5, unit: 'SECONDS') //timeout after some metioned time
        timeout(time: 30, unit: 'MINUTES') // generally 30 min or based on project
    }
     /* parameters{
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    } */
    stages{
        stage('Init'){
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform init -reconfigure
                        """
                    }                    
                }
            }
        }
    }
     
    post{
        always{
            echo 'I will always say Hello again!'
            deleteDir() //it will deletes the directory
        }
        failure{
            echo 'I will run when pipeline is failed'
        }
        success{
            echo 'I will run when pipeline is success'
        }
    }
}